language: c
compiler: gcc
branches:
  only:
    - master
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq postgresql postgresql-client postgresql-server-dev-all librabbitmq-dev
  - gcc --version
  - sudo apt-get install -qq gcc-4.9
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9
install: make
env:
  - LANG="en_US.UTF-8"
os:
  - linux
