language: c
compiler: gcc
branches:
  only:
    - master
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq postgresql postgresql-client postgresql-server-dev-all librabbitmq-dev
  - sudo apt-get install -qq gcc-4.8
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 99
  - gcc --version
install: make
script: make
env:
  - LANG="en_US.UTF-8"
os:
  - linux
