language: c
compiler: gcc
branches:
  only:
    - master
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq postgresql postgresql-client postgresql-server-dev-all librabbitmq-dev
install: make
env:
  - LANG="en_US.UTF-8"
os:
  - linux
